// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBplCAr4rqC5gk4-HtbWQz6XlUwuTO-M0k',
    appId: '1:447237837831:web:00a4e6967db03bf4af46a2',
    messagingSenderId: '447237837831',
    projectId: 'flutterauth-34a07',
    authDomain: 'flutterauth-34a07.firebaseapp.com',
    storageBucket: 'flutterauth-34a07.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNiMWiQLgALF-ZFLVK8fyMzFFz_3JsE8I',
    appId: '1:447237837831:android:74c65dd9e184c18aaf46a2',
    messagingSenderId: '447237837831',
    projectId: 'flutterauth-34a07',
    storageBucket: 'flutterauth-34a07.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXmXmhZWTW1DHlqG1vVUNL6hSy_EKtlZ0',
    appId: '1:447237837831:ios:d80fce23c693daf4af46a2',
    messagingSenderId: '447237837831',
    projectId: 'flutterauth-34a07',
    storageBucket: 'flutterauth-34a07.appspot.com',
    iosBundleId: 'com.example.onboardingScreen',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAXmXmhZWTW1DHlqG1vVUNL6hSy_EKtlZ0',
    appId: '1:447237837831:ios:0779aec7cc1b3c62af46a2',
    messagingSenderId: '447237837831',
    projectId: 'flutterauth-34a07',
    storageBucket: 'flutterauth-34a07.appspot.com',
    iosBundleId: 'com.example.onboardingScreen.RunnerTests',
  );
}
